# C?u hình Gmail SMTP
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2

# Email
mail.from=stemshop.system@gmail.com
mail.password=gmilmlnmvuereosb

# Base URL cua web (khi chay local)
app.base.url=http://localhost:8080
#  Base URL cua web (khi deploy lên VPS)
#app.base.url=http://103.165.144.135:8080