# C?u hình Gmail SMTP
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2

# Email g?i ?i
mail.from=stemshop.system@gmail.com
mail.password=gmilmlnmvuereosb

# Base URL c?a web (khi ch?y local)
app.base.url=http://localhost:8080
#  Base URL c?a web (khi cdeploy lên VPS)
# app.base.url=http://103.165.144.135:8080