# C?u hình VNPay
vnp.vnp_TmnCode=86RNNWDA
vnp.vnp_HashSecret=Z2HUX4CK50QMTJRQ248U0XY1OSL8PXG7
vnp.vnp_Url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# khi ch?y local
vnp.vnp_ReturnUrl=http://localhost:8080/vnpay-return
# Khi deploy
#vnp.vnp_ReturnUrl=http://103.165.144.135:8080/vnpay-return
vnp.vnp_Version=2.1.0
vnp.vnp_Command=pay
vnp.vnp_CurrCode=VND
vnp.vnp_Locale=vn
vnp.vnp_OrderType=other